### PR TITLE
Fixed the documentation & saving keys

### LINKED ISSUE #8: _keys should be saved somewhere.
Right now the `_keys` field is always empty until you save something. 

We should save all the keys. So we always know what is saved and what is not saved.

### PR DESCRIPTION
**Pull request by vanlooverenkoen**
Fixed #8

### CODE REVIEW

File: lib/src/flutter_secure_file_storage.dart [hunk 1]
```diff
@@ -27,6 +27,13 @@ class FlutterSecureFileStorage {
 
   /// Encrypts and saves the [key] with the given [value].
```
Comment (NicolaVerbeeck) [inline lib/src/flutter_secure_file_storage.dart:28]: This sentence is confusing

File: lib/src/flutter_secure_file_storage.dart [hunk 2]
```diff
@@ -46,11 +53,16 @@ class FlutterSecureFileStorage {
     if (encrypted == null) return delete(key: key);
     await _secureStorage.saveIV(key, encrypted.iv);
     await _fileStorage.write(_filename(key), encrypted.value);
-    _keys.add(key);
+    _keys.add(base64Encode(utf8.encode(key)));
```
Comment (NicolaVerbeeck) [inline lib/src/flutter_secure_file_storage.dart:56]: Encoding is not used to read

File: lib/src/flutter_secure_file_storage.dart [hunk 3]
```diff
@@ -67,6 +79,10 @@ class FlutterSecureFileStorage {
   }
 
   /// Returns true if the storage contains the given [key].
+  ///
```
Comment (NicolaVerbeeck) [inline lib/src/flutter_secure_file_storage.dart:82]: No need to add this info here

File: lib/src/flutter_secure_file_storage.dart [hunk 4]
```diff
@@ -46,11 +53,16 @@ class FlutterSecureFileStorage {
...
     await _secureStorage.saveIV(key, encrypted.iv);
     await _fileStorage.write(_filename(key), encrypted.value);
-    _keys.add(key);
+    _keys.add(base64Encode(utf8.encode(key)));
     _updateKeys();
   }
 
   /// Decrypts and returns the value for the given [key] or null if [key] is not in the storage.
+  ///
+  /// The key itself is used to get the:
```
Comment (NicolaVerbeeck) [inline lib/src/flutter_secure_file_storage.dart:62]: No need to add this info here

File: lib/src/flutter_secure_file_storage.dart [hunk 5]
```diff
@@ -80,6 +96,8 @@ class FlutterSecureFileStorage {
   }
 
   /// Deletes associated value for the given [key].
+  ///
+  /// The key itself is used to delete the IV & encryptionKey & file
```
Comment (NicolaVerbeeck) [inline lib/src/flutter_secure_file_storage.dart:100]: 'All associated data for the given key is removed'

**Review by NicolaVerbeeck — APPROVED** [review]
